time = input("Enter a number from 1 to 12: ")
items = input("Enter an item (plural): ")
name = input("Enter a name: ")
scream = input("Enter a scream: ")
action = input("Enter an action: ")

print('It was ' + time + ' o\'clock when I heard a knock at the door.')
print('I opened the door and there was a box full of ' + items + ' with a note saying "From Mr. ' + name.title() + '."')
print('Just as I closed the door I heard a scream "' + scream.upper() + '."')
print('I froze in place and all I could do was ' + action + '.')
